version: '3.8'

services:
   db:
    image: postgres:17
    container_name: database_lexicon_app
    ports:
      - 5432:5432
    volumes:
      - lexicon_postgres:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=lexicon_app_db
     - POSTGRES_USER=django
     - POSTGRES_PASSWORD=1234
  
   web1:
    image: lexicon_app
    container_name: lexicon_app1
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    depends on:
      - db

volumes:
  lexicon_postgres:
