version: '3.8'

services:
   db:
    image: postgres:17
    container_name: database_lexicon_app
    ports:
      - 5432:5432
    volumes:
      - lexicon_postgres:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=lexicon_app_db
     - POSTGRES_USER=django
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  
   web1:
    image: stevetasticsteve/lexicon
    container_name: lexicon_app1
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DEBUG=${DEBUG}
      - HTTPS=${HTTPS}
    depends_on:
      - db

volumes:
  lexicon_postgres:
