services:
   db:
    image: postgres:17
    container_name: database_lexicon_app
    restart: always
    volumes:
      - lexicon_postgres:/var/lib/postgresql/data
    env_file:
      - .env
  
   web1:
    image: stevetasticsteve/lexicon
    container_name: lexicon_app1
    restart: always
    volumes:
      - ./data/logs:/app/data/logs
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
   
   celery:
    image: stevetasticsteve/celery_lexicon
    container_name: celery_lexicon
    restart: always
    command: celery -A config worker
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - web1
      - redis
      - db
    
   redis:
    image: redis
    container_name: redis_lexicon
    restart: always
   
   watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 lexicon_app1 celery_lexicon

volumes:
  lexicon_postgres:
