services:
   db:
    image: postgres:17
    container_name: database_lexicon_app
    restart: always
    volumes:
      - lexicon_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  
   web1:
    container_name: lexicon_app1
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile 
    volumes:
      - ../apps:/app/apps:ro
      - ../config:/app/config:ro
      - ../data/logs:/app/data/logs
      - ../templates:/app/templates:ro
      - ../import_kovol_data.py:/app/import_kovol_data.py:ro
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
   
   celery:
    container_name: celery_lexicon
    build:
      context: ../
      dockerfile: docker/CeleryDockerfile
    volumes:
      - ../apps:/app/apps:ro
      - ../config:/app/config:ro
      - ../data/logs:/app/data/logs
      - ../templates:/app/templates:ro
    restart: always
    command: celery -A config worker
    env_file:
      - .env

    depends_on:
      - web1
      - redis
      - db
    
   redis:
    image: redis
    container_name: redis_lexicon
    restart: always
   
volumes:
  lexicon_postgres:
