# Generated by Django 5.2.4 on 2025-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('import', 'Help importing Data'), ('other', 'Other')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
