# Generated by Django 5.2.4 on 2025-09-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_handled_alter_feedback_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug report'), ('feature', 'Feature request'), ('new', 'I wish to create a new project'), ('permission', 'I need permission to edit a project'), ('import', 'Help importing data'), ('other', 'Other')], max_length=10),
        ),
    ]
