# Generated by Django 5.1.3 on 2024-11-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LexiconProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=25, verbose_name='Language name')),
                ('language_code', models.CharField(max_length=4, unique=True, verbose_name='3 Digit ethnologue language code')),
            ],
        ),
    ]
