# Generated by Django 5.2.4 on 2025-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lexiconentry",
            name="unique_text_per_project",
        ),
        migrations.AddField(
            model_name="lexiconentry",
            name="disambiguation",
            field=models.CharField(
                blank=True,
                default="",
                help_text='A short disambiguation tag if entries need to have the same headword (e.g., "to see" vs. "to be"). Leave blank if not needed.',
                max_length=60,
            ),
        ),
        migrations.AddConstraint(
            model_name="lexiconentry",
            constraint=models.UniqueConstraint(
                fields=("project", "text", "disambiguation"),
                name="unique_text_per_project",
            ),
        ),
    ]
