# Generated by Django 5.2.4 on 2025-09-05 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0002_remove_lexiconentry_unique_text_per_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lexiconproject',
            options={'ordering': ['language_name'], 'permissions': [('edit_lexiconproject', 'Can edit this lexicon project')]},
        ),
    ]
