# Generated by Django 5.1.3 on 2025-05-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0006_alter_ignoreword_options_alter_lexiconentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('n', 'noun'), ('pn', 'proper noun'), ('adj', 'adjective'), ('v', 'verb'), ('adv', 'adverb'), ('com', 'compound verb'), ('prn', 'pronoun'), ('rel', 'relator/preposition'), ('uk', 'uknown')], help_text='Part of speech this paradigm is for (e.g., verb, noun)', max_length=5)),
                ('row_labels', models.JSONField(help_text='List of row labels for the paradigm grid')),
                ('column_labels', models.JSONField(help_text='List of column labels for the paradigm grid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexicon.lexiconproject')),
            ],
        ),
    ]
