# Generated by Django 5.1.3 on 2025-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0008_alter_paradigm_name_conjugation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugation',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='conjugation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
