# Generated by Django 5.1.3 on 2025-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0009_alter_conjugation_column_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conjugation',
            constraint=models.UniqueConstraint(fields=('word', 'paradigm', 'row', 'column'), name='unique_conjugation_position'),
        ),
    ]
