# Generated by Django 5.1.3 on 2025-05-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0010_conjugation_unique_conjugation_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conjugation',
            options={'verbose_name': 'Conjugation', 'verbose_name_plural': 'Conjugations'},
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='column',
            field=models.IntegerField(blank=True, default=0, help_text='The column index in the paradigm grid.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='conjugation',
            field=models.CharField(blank=True, default='test', help_text='The actual conjugated form of the word.', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='paradigm',
            field=models.ForeignKey(help_text='The paradigm that defines the conjugation structure.', on_delete=django.db.models.deletion.CASCADE, to='lexicon.paradigm'),
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='row',
            field=models.IntegerField(blank=True, default=0, help_text='The row index in the paradigm grid.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='word',
            field=models.ForeignKey(help_text='The word that this conjugation belongs to.', on_delete=django.db.models.deletion.CASCADE, to='lexicon.lexiconentry'),
        ),
        migrations.AddConstraint(
            model_name='paradigm',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_paradigm_name_per_project'),
        ),
    ]
