# Generated by Django 5.1.3 on 2025-05-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0011_alter_conjugation_options_alter_conjugation_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexiconentry',
            name='paradigms',
            field=models.ManyToManyField(blank=True, help_text='Paradigms that this word can use for conjugation/declension', to='lexicon.paradigm'),
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='column',
            field=models.IntegerField(help_text='The column index in the paradigm grid.'),
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='row',
            field=models.IntegerField(help_text='The row index in the paradigm grid.'),
        ),
    ]
