# Generated by Django 5.1.3 on 2025-06-05 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0012_lexiconentry_paradigms_alter_conjugation_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexiconentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lexicon.lexiconproject'),
        ),
        migrations.AlterField(
            model_name='lexiconentry',
            name='tok_ples',
            field=models.CharField(help_text='The language the project is focussed on.', max_length=60, verbose_name='Tok Ples'),
        ),
        migrations.AddConstraint(
            model_name='lexiconentry',
            constraint=models.UniqueConstraint(fields=('project', 'tok_ples'), name='unique_tok_ples_per_project'),
        ),
    ]
