# Generated by Django 5.1.3 on 2025-06-08 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0013_alter_lexiconentry_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('spelling', 'Spelling Variant'), ('dialect', 'Dialectal Variant'), ('abbrv', 'Abbreviation')], max_length=15)),
                ('text', models.CharField(help_text='write the variation here', max_length=100, verbose_name='variation')),
                ('included_in_spellcheck', models.BooleanField(default=False, help_text='Should word be marked in spellcheck as acceptable?')),
                ('included_in_search', models.BooleanField(default=False, help_text='Should word appear in search results?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spellingvariation',
            name='word',
        ),
        migrations.AddField(
            model_name='lexiconentry',
            name='search',
            field=models.TextField(blank=True, help_text='automatically generated search terms', null=True),
        ),
        migrations.AddIndex(
            model_name='lexiconentry',
            index=models.Index(fields=['search'], name='lexicon_lex_search_34e5fe_idx'),
        ),
        migrations.AddField(
            model_name='variation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='lexicon.lexiconentry'),
        ),
        migrations.DeleteModel(
            name='SpellingVariation',
        ),
    ]
