# Generated by Django 5.1.3 on 2025-06-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0014_variation_remove_spellingvariation_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the affix', max_length=40)),
                ('applies_to', models.CharField(choices=[('n', 'noun'), ('pn', 'proper noun'), ('adj', 'adjective'), ('v', 'verb'), ('adv', 'adverb'), ('com', 'compound verb'), ('prn', 'pronoun'), ('rel', 'relator/preposition'), ('uk', 'uknown')], help_text='Part of speech this affix is for (e.g., verb, noun)', max_length=5)),
                ('affix_letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], help_text='Single letter representing the affix.', max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affixes', to='lexicon.lexiconproject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'affix_letter'), name='unique_affix_letter_per_project')],
            },
        ),
    ]
