# Generated by Django 5.1.3 on 2025-06-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0015_affix'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexiconentry',
            name='affixes',
            field=models.ManyToManyField(blank=True, help_text='Affixes that can be used with this entry.', related_name='entries', to='lexicon.affix'),
        ),
    ]
