# Generated by Django 5.1.3 on 2025-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0017_alter_lexiconproject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoreword',
            name='tok_ples',
            field=models.CharField(help_text='Word to add to spell check.', max_length=60),
        ),
        migrations.AddConstraint(
            model_name='ignoreword',
            constraint=models.UniqueConstraint(fields=('project', 'tok_ples'), name='ignore_word_unique_tok_ples_per_project'),
        ),
    ]
