# Generated by Django 5.2.4 on 2025-07-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0018_alter_ignoreword_tok_ples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(help_text='English translation for this sense.', max_length=60, verbose_name='English')),
                ('oth_lang', models.CharField(blank=True, help_text='Translation in project 2nd language for this sense.', max_length=60, null=True, verbose_name='Other language')),
                ('example', models.TextField(blank=True, help_text='Example sentence or usage.', null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of this sense for the entry.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='ignoreword',
            options={'ordering': ['text']},
        ),
        migrations.AlterModelOptions(
            name='lexiconentry',
            options={'ordering': ['text']},
        ),
        migrations.RemoveConstraint(
            model_name='ignoreword',
            name='ignore_word_unique_tok_ples_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='lexiconentry',
            name='unique_tok_ples_per_project',
        ),
        migrations.RenameField(
            model_name='ignoreword',
            old_name='tok_ples',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='lexiconentry',
            name='eng',
        ),
        migrations.RemoveField(
            model_name='lexiconentry',
            name='oth_lang',
        ),
        migrations.RemoveField(
            model_name='lexiconentry',
            name='tok_ples',
        ),
        migrations.RemoveField(
            model_name='lexiconproject',
            name='tok_ples_validator',
        ),
        migrations.AddField(
            model_name='lexiconentry',
            name='text',
            field=models.CharField(default='default', help_text='The lexicon entry text for the entry, in the language of the project.', max_length=60, verbose_name='Tok Ples'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lexiconproject',
            name='text_validator',
            field=models.CharField(blank=True, help_text='An optional regex to represent which characters are allowed in language entries. If set entries can only be saved if they only contain these characters. [abc] for example only allows the characters a, b and c.', max_length=60, null=True, verbose_name='Regex language text validator'),
        ),
        migrations.AddConstraint(
            model_name='ignoreword',
            constraint=models.UniqueConstraint(fields=('project', 'text'), name='ignore_word_unique_text_per_project'),
        ),
        migrations.AddConstraint(
            model_name='lexiconentry',
            constraint=models.UniqueConstraint(fields=('project', 'text'), name='unique_text_per_project'),
        ),
        migrations.AddField(
            model_name='sense',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='lexicon.lexiconentry'),
        ),
    ]
