# Generated by Django 5.2.4 on 2025-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0019_sense_alter_ignoreword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affix',
            name='applies_to',
            field=models.CharField(choices=[('n', 'noun'), ('pn', 'proper noun'), ('adj', 'adjective'), ('v', 'verb'), ('adv', 'adverb'), ('com', 'compound verb'), ('prn', 'pronoun'), ('rel', 'relator/preposition'), ('ph', 'phrase'), ('uk', 'uknown')], help_text='Part of speech this affix is for (e.g., verb, noun)', max_length=5),
        ),
        migrations.AlterField(
            model_name='lexiconentry',
            name='pos',
            field=models.CharField(blank=True, choices=[('n', 'noun'), ('pn', 'proper noun'), ('adj', 'adjective'), ('v', 'verb'), ('adv', 'adverb'), ('com', 'compound verb'), ('prn', 'pronoun'), ('rel', 'relator/preposition'), ('ph', 'phrase'), ('uk', 'uknown')], max_length=5, null=True, verbose_name='part of speech'),
        ),
        migrations.AlterField(
            model_name='lexiconentry',
            name='text',
            field=models.CharField(help_text='The lexicon entry text for the entry, in the language of the project.', max_length=60, verbose_name='Language text'),
        ),
        migrations.AlterField(
            model_name='lexiconproject',
            name='affix_file',
            field=models.TextField(default='# Hunspell affix file for LANGUAGE by NTMPNG\nSET UTF-8\nTRY aeiouAEIOUpbtdkgjmnfsvhlrwyPBTDKGJMNFSVHLRWY\nWORDCHARS -\n\nNOSUGGEST !', help_text='See https://www.systutorials.com/docs/linux/man/4-hunspell/'),
        ),
        migrations.AlterField(
            model_name='paradigm',
            name='part_of_speech',
            field=models.CharField(choices=[('n', 'noun'), ('pn', 'proper noun'), ('adj', 'adjective'), ('v', 'verb'), ('adv', 'adverb'), ('com', 'compound verb'), ('prn', 'pronoun'), ('rel', 'relator/preposition'), ('ph', 'phrase'), ('uk', 'uknown')], help_text='Part of speech this paradigm is for (e.g., verb, noun)', max_length=5),
        ),
        migrations.AlterField(
            model_name='sense',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Senses with lower numbers appear first.'),
        ),
    ]
