# Generated by Django 5.2.4 on 2025-08-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexicon', '0020_alter_affix_applies_to_alter_lexiconentry_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugation',
            name='word',
            field=models.ForeignKey(help_text='The word that this conjugation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='conjugations', to='lexicon.lexiconentry'),
        ),
    ]
